### ISSUE TITLE
epg2xml.py "requests.exceptions.ChunkedEncodingError"

### ISSUE THREAD

**Issue by yesmbt** [wonipapa/epg2xml#17]
HTS Tvheadend 4.3-228~g4fc1a6c-dirty.
python 2.7.13
epg2xml 1.1.9 를 사용하고 있습니다.
LG, 2일, s(socket)
epg2xml.php는 잘 작동합니다. 그런데 epg2xml.py가 에러를 일으킵니다.

에러코드는 아래와 같습니다.-----------------------------------------------------------------

Traceback (most recent call last):
  File "epg2xml.py", line 854, in <module>
    getEpg()
  File "epg2xml.py", line 116, in getEpg
    GetEPGFromSK(ChannelInfo)
  File "epg2xml.py", line 312, in GetEPGFromSK
    response = requests.get(url, params=params, headers=ua)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 652, in send
    r.content
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 825, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 750, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))

에러코드 끝-------------------------------------------------------------------------------

**Comment by wonipapa** [comment]
예외처리에 관한 수정작업중입니다.
