### ISSUE TITLE
어제부터 epg2xml 문제가 생겼습니다.

### ISSUE THREAD

**Issue by moodcela** [wonipapa/epg2xml#72]
안녕하세요.
잘 만들어주신 프로그램 감사하게 사용하게 있었는데요
어제부터 오류가 생기며 문제가 생겼습니다.

py 파이썬 파일을 사용해 이용했었고
에러 스크린샷은 다음과 같습니다.

![epg](https://user-images.githubusercontent.com/20749641/34453698-eb4d6628-ed9d-11e7-8ff0-150d626fb198.PNG)

http://m.iscs.co.kr/sub/02/data.asp
사이트에 직접 들어가보니 페이지가 없어진것 같은데 관련이 있는건지 모르겠내요.

갑자기 왜그럴까요... 잘 사용하다가 안되니 불편합니다...

**Comment by donut88** [comment]
같은증상 tvheadend 로그 첨부합니다~

2017-12-31 00:58:50.772 xmltv: /usr/bin/tv_grab_kr_kt: grab /usr/bin/tv_grab_kr_kt
2017-12-31 00:58:50.774 spawn: Executing "/usr/bin/tv_grab_kr_kt"
2017-12-31 00:59:04.569 spawn: Traceback (most recent call last):
2017-12-31 00:59:04.569 spawn:   File "/epg2xml/epg2xml.py", line 1267, in 
2017-12-31 00:59:04.570 spawn:     getEpg()
2017-12-31 00:59:04.570 spawn:   File "/epg2xml/epg2xml.py", line 134, in getEpg
2017-12-31 00:59:04.571 spawn:     GetEPGFromIscs(ChannelInfo)
2017-12-31 00:59:04.571 spawn:   File "/epg2xml/epg2xml.py", line 536, in GetEPGFromIscs
2017-12-31 00:59:04.571 spawn:     response.raise_for_status()
2017-12-31 00:59:04.571 spawn:   File "/usr/lib/python2.7/site-packages/requests/models.py", line 862, in raise_for_status
2017-12-31 00:59:04.572 spawn:     raise HTTPError(http_error_msg, response=self)
2017-12-31 00:59:04.572 spawn: requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://m.iscs.co.kr/sub/02/data.asp

**Comment by eastmate** [comment]
일단 연휴라서 wonipapa님께서 쉬시지 않을까싶어 주제넘지만 임시해결방법 말씀드려봅니다.

Channel.json에 있는 채널 중에서 Source가 ISCS 인 채널에 문제가 발생하는 듯 보여집니다.

제 경우는 위와 같은 에러와 함께 epg 업데이트가 도중에 중단되더군요.

이전에 쓰던 Channel.json 이 있어 적용했더니 ISCS가 없어서 그런지 업데이트가 되었습니다.

저처럼 ISCS 가 없는 Channel.json 있으시면 그걸로 이용하시고,

다른 채널이라도 업데이트 하시려면 ISCS 인 채널을 epg2xml.json의  MyChannels에서 번호를 임시로 삭제하셔보면 어떨까 합니다.

물론 epg2xml.json 백업해두시고요.

임시로라도 해결되시길 바랍니다.

**Comment by yesmbt** [comment]
데이터를 가저온 경로가 바뀐 것 같습니다.
소스를 보시고 url='http://m.iscs.co.kr/sub/02/data.asp' 줄을 찿으시고.
바뀐주소 url='http://m.iscs.co.kr/service/sub/win_02_04.asp'로 바꾸고 하니 다시 잘 되네요

**Comment by moondaeho** [comment]
위 분 말씀처럼 일단 원본파일 백업하시고,
채널을 하나씩 지우기는 시간이 많이 걸리니 임시방편으로
epg2xml.py에서 133,134라인의 하기 문장을 #으로 주석처리 하시면 됩니다.
ISCS로 받아오던 채널 정보는 안나오지 싶습니다.

        #elif ChannelSource == 'ISCS':
          #  GetEPGFromIscs(ChannelInfo)

**Comment by desperado4** [comment]
새해 복 많이 받으세요!!!!

오늘 보니 epg 가 안나와서 로그 확인해보니

2018-01-01 13:44:08.031 spawn:   File "/home/hts/epg2xml.py", line 1267, in 

2018-01-01 13:44:08.033 spawn:     getEpg()

2018-01-01 13:44:08.033 spawn:   File "/home/hts/epg2xml.py", line 134, in getEpg

2018-01-01 13:44:08.034 spawn:     #            GetEPGFromIscs(ChannelInfo)

2018-01-01 13:44:08.034 spawn:   File "/home/hts/epg2xml.py", line 536, in GetEPGFromIscs

2018-01-01 13:44:08.035 spawn:     response.raise_for_status()

2018-01-01 13:44:08.035 spawn:   File "/usr/lib/python2.7/dist-packages/requests/models.py", line 862, in raise_for_status

2018-01-01 13:44:08.036 spawn:     raise HTTPError(http_error_msg, response=self)

2018-01-01 13:44:08.036 spawn: requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://m.iscs.co.kr/sub/02/data.asp


iscs 서버(?) 에서 정보를 못 가져오는것 같아 일단은 epg2xml.py 의 elif ChannelSource == 'ISCS':
 GetEPGFromIscs(ChannelInfo)
에 # 주석 처리를 하였습니다

**Comment by wonipapa** [comment]
1.2.4 버전에 수정했습니다.

**Comment by desperado4** [comment]
금방 업데이트 돼었네요
언제나 감사합니다^^
