### ISSUE TITLE
SK 소스 오류

### ISSUE THREAD

**Issue by eastmate** [wonipapa/epg2xml#84]
지난 번 말씀드린  Id : 173 SkyDrama 오류가 다시 보여서 제보드립니다.(이번엔 3일치)

마찬가지로 SKB는 되고 SK로는 안되며, 에러메세지는 아래와 같습니다.

1.2.4 버전이었을 때,
Traceback (most recent call last):
File "/root/epg/epg2xml.py", line 1264, in 
getEpg()
File "/root/epg/epg2xml.py", line 126, in getEpg
GetEPGFromSK(ChannelInfo)
File "/root/epg/epg2xml.py", line 359, in GetEPGFromSK
writeProgram(programdata)
File "/root/epg/epg2xml.py", line 1068, in writeProgram
if programdata['desc'] : desc = desc + '\n' + escape(programdata['desc'])
File "/usr/lib/python2.7/xml/sax/saxutils.py", line 32, in escape
data = data.replace("&", "&")
AttributeError: 'list' object has no attribute 'replace'

1.2.4p2 버전에서,
Traceback (most recent call last):
  File "/root/epg/epg2xml.py", line 1266, in <module>
    getEpg()
  File "/root/epg/epg2xml.py", line 126, in getEpg
    GetEPGFromSK(ChannelInfo)
  File "/root/epg/epg2xml.py", line 359, in GetEPGFromSK
    writeProgram(programdata)
  File "/root/epg/epg2xml.py", line 1070, in writeProgram
    if programdata['desc'] : desc = desc + '\n' + escape(programdata['desc'])
  File "/usr/lib/python2.7/xml/sax/saxutils.py", line 32, in escape
    data = data.replace("&", "&amp;")
AttributeError: 'list' object has no attribute 'replace'

제보드린 이후에 정상으로 돌아와서 못보셨을 것 같아 다시 제보드립니다.

디폴트인 SKY로 하면 문제없이 작동합니다. 감사합니다.

**Comment by wonipapa** [comment]
2월중까지는 제가 업무 관계로 3월 정도에 수정하도록 해보겠습니다.
제보 감사합니다.

**Comment by eastmate** [comment]
많이 바쁘시군요. 디폴트 값으로 이용시 전혀 문제 없으므로 천천히 하시거나 안하셔도 될 것 같습니다.

항상 감사드립니다.

**Comment by wonipapa** [comment]
수정완료

**Comment by eastmate** [comment]
급한 것은 전혀 아니지만, 지금 수정작업 중이신 것 같아 올려봅니다.

딱히 어디에 올릴까 싶다가 감사인사 전하며 이 곳에 올려봅니다.

SKB
채널명 : 'Life N' → 'Life U' 
채널번호 : 215번 변경 없음 

3.1일자로 변경되었습니다. 

바쁘신 와중에도 항상 수정해주셔서 감사합니다.

**Comment by wonipapa** [comment]
주말 지나서 바꿔 놓도록 하겠습니다

**Comment by wonipapa** [comment]
채널 반영했습니다.

**Comment by eastmate** [comment]
감사합니다!!

**Comment by eastmate** [comment]
새 이슈를 작성하기 보다 기존 이슈에 댓글을 남깁니다.

오랜 기간 정말 감사했습니다.

하시는일 모두 이루시길 바라고, 항상 행운과 행복이 깃들기를 기원합니다.
